/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "app_constants.h"

namespace Visualization {

const appConstants g_app_constants;

appConstants::appConstants() {
}

} // namespace

