/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef app_CONSTANTS_H
#define app_CONSTANTS_H

#include "app_types.h"

namespace Visualization {

class appConstants {
 public:
  appConstants();

};

extern const appConstants g_app_constants;

} // namespace

#endif
